# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0027_auto_20160901_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='ordering',
            field=models.IntegerField(unique=True),
        ),
    ]
