# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('documentation', '0032_remove_article_can_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='edit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
