# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0033_article_edit_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
