# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-29 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0034_auto_20161007_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visitor_counter',
            field=models.IntegerField(default=0),
        ),
    ]
