name: fidia-conda

channels:
  - astropy

dependencies:
  - python=3.5
  - astropy
  - Cython
  - matplotlib
  - numpy
  - Pillow
  - sortedcontainers
  - numpy
  - cached_property
  - sqlalchemy
  - sphinx
  - matplotlib
  - pytest
  - pytest-benchmark
  - pandas
  
#   - pip:
#       - dependency_from_pip
