name: fidia-conda

channels:
  - astropy

dependencies:
  - python=3.5
  - astropy
  - Cython
  - matplotlib
  - numpy
  - Pillow
  - sortedcontainers
  - numpy
  - sqlalchemy
  - sphinx
  - matplotlib
  - pytest
  - pytest-benchmark
  - pandas

   - pip:
       - cached_property
