# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cutout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objId', models.IntegerField(blank=True)),
                ('ra', models.FloatField(blank=True)),
                ('dec', models.FloatField(blank=True)),
                ('radius', models.FloatField(blank=True)),
                ('greyscale', models.BooleanField(default=True)),
                ('bands', models.CharField(choices=[('CH', 'Chandra'), ('GA', 'GALEX'), ('HST', 'HST'), ('SDSS', 'SDSS'), ('VIKING', 'VIKING')], default='SDSS', max_length=5)),
                ('rgb', models.BooleanField(default=False)),
                ('rgbRed', models.CharField(choices=[('CH', 'Chandra'), ('GA', 'GALEX'), ('HST', 'HST'), ('SDSS', 'SDSS'), ('VIKING', 'VIKING')], default='SDSS', max_length=1)),
                ('rgbGreen', models.CharField(choices=[('CH', 'Chandra'), ('GA', 'GALEX'), ('HST', 'HST'), ('SDSS', 'SDSS'), ('VIKING', 'VIKING')], default='VIKING', max_length=1)),
                ('rgbBlue', models.CharField(choices=[('CH', 'Chandra'), ('GA', 'GALEX'), ('HST', 'HST'), ('SDSS', 'SDSS'), ('VIKING', 'VIKING')], default='SDSS', max_length=1)),
                ('contourBand', models.CharField(choices=[('CH', 'Chandra'), ('GA', 'GALEX'), ('HST', 'HST'), ('SDSS', 'SDSS'), ('VIKING', 'VIKING')], default='SDSS', max_length=1)),
                ('contourLevels', models.FloatField(blank=True)),
                ('inputScaling', models.CharField(choices=[('CH', 'Chandra'), ('GA', 'GALEX'), ('HST', 'HST'), ('SDSS', 'SDSS'), ('VIKING', 'VIKING')], default='SDSS', max_length=1)),
                ('stretchScale', models.FloatField(default=1)),
                ('axisStyle', models.CharField(choices=[('BASIC', 'Basic'), ('INSET', 'Inset'), ('NONE', 'None')], default='BASIC', max_length=1)),
                ('scaleBar', models.BooleanField(default=False)),
                ('scaleBarz', models.FloatField(blank=True)),
                ('imageColor', models.CharField(choices=[('HEAT', 'Heat'), ('GREY', 'grey')], max_length=1)),
                ('invertColor', models.BooleanField(default=False)),
                ('overplotGAMAsources', models.BooleanField(default=False)),
                ('overplotGAMAapertures', models.BooleanField(default=False)),
                ('overplotIOTAapertures', models.BooleanField(default=False)),
                ('overplotSAMIsources', models.BooleanField(default=False)),
            ],
        ),
    ]
