# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_app', '0010_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
