# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='order',
            new_name='article_order',
        ),
    ]
