# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('survey_team', models.CharField(choices=[('NA', 'Not applicable'), ('GAMA', 'GAMA'), ('SAMI', 'SAMI'), ('GALAH', 'GALAH')], default='NA', max_length=1)),
            ],
        ),
    ]
