# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_bugreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='message',
            field=models.CharField(max_length=10000),
        ),
    ]
