# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20170501_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='survey_team',
            field=models.CharField(choices=[('NA', 'Not applicable'), ('GAMA', 'GAMA'), ('SAMI', 'SAMI'), ('GALAH', 'GALAH')], default='NA', max_length=100),
        ),
    ]
