# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 01:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feature', '0002_auto_20170407_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='votes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vote',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature.Feature'),
        ),
        migrations.AddField(
            model_name='vote',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
