# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0005_auto_20170408_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(default='Long description goes here', max_length=1000),
        ),
    ]
