# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 02:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0006_feature_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_feature', to=settings.AUTH_USER_MODEL),
        ),
    ]
