# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0007_auto_20170408_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='user',
        ),
        migrations.AddField(
            model_name='feature',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_votes', to='feature.Feature'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
    ]
