# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0008_auto_20170408_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='feature',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='votes',
            new_name='vote',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
