# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 02:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feature', '0009_auto_20170408_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feature',
            name='vote',
            field=models.IntegerField(default=1),
        ),
    ]
