# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0011_auto_20170408_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='vote',
        ),
    ]
