# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0012_remove_feature_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
