# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0013_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feature.Feature'),
        ),
    ]
