# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0014_auto_20170408_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='feature',
        ),
        migrations.AddField(
            model_name='feature',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
