# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0015_auto_20170409_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='vote_score',
        ),
    ]
