# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0021_auto_20170409_1400'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'feature')]),
        ),
    ]
