# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0022_auto_20170409_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
