# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0023_feature_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='is_accepted',
            new_name='is_approved',
        ),
    ]
