# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 05:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0028_auto_20170411_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
