# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0029_feature_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
