# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20170222_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='queryBuilderState',
            field=models.TextField(null=True),
        ),
    ]
