# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0008_auto_20170222_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='queryBuilderState',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='queryResults',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
