# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0009_auto_20170222_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='queryBuilderState',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='query',
            name='queryResults',
            field=models.TextField(blank=True, default=''),
        ),
    ]
