# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0010_auto_20170222_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='queryResults',
            field=models.TextField(blank=True, default={}),
        ),
    ]
