# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 00:26
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0011_auto_20170222_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='queryResults',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
