# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0015_query_isfinished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='isFinished',
            new_name='isCompleted',
        ),
    ]
