# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0016_auto_20170314_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='queryResults',
            new_name='results',
        ),
    ]
