# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0017_auto_20170314_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='queryBuilderState',
            field=models.CharField(blank=True, default='', max_length=1000000),
        ),
    ]
