# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0019_auto_20170329_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='hasError',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='query',
            name='isInvalid',
            field=models.BooleanField(default=False),
        ),
    ]
