# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 05:03
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0020_auto_20170329_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='queryBuilderState',
            field=jsonfield.fields.JSONField(blank=True, default=''),
        ),
    ]
