# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 23:49
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0021_auto_20170329_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='results',
            field=jsonfield.fields.JSONField(blank=True, default=''),
        ),
    ]
