# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 01:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0022_auto_20170331_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='queryBuilderState',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='query',
            name='results',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
        ),
    ]
