# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 06:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0024_auto_20170418_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='results',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
