# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 06:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0025_auto_20170418_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='isInvalid',
        ),
        migrations.AddField(
            model_name='query',
            name='error',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='query',
            name='hasError',
            field=models.BooleanField(default=False),
        ),
    ]
