# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0026_auto_20170420_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='error',
        ),
    ]
