# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0029_auto_20170420_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='testField',
            field=models.BooleanField(default=False),
        ),
    ]
