# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0033_remove_query_testfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='title',
            field=models.CharField(blank=True, default='My Query', max_length=1000),
        ),
    ]
