# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0035_auto_20170503_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_builder_state',
            field=models.TextField(blank=True, default=''),
        ),
    ]
