# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import query.models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0036_auto_20170503_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='table_name',
            field=models.CharField(default=query.models.generate_random_string, max_length=100),
        ),
    ]
