# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0037_auto_20170503_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='csv_completed',
            field=models.BooleanField(default=False),
        ),
    ]
